### ISSUE TITLE
Bug report - userIdMatch is null.

### ISSUE THREAD

**Issue by lacicloud** [markspolakovs/BetterSMS#1]
Hi Marks,

Nice work! 
Here is a message I receive periodically on Google Chrome (Version 69.0.3497.100 (Official Build) (64-bit)). 

A required invariant in BetterSMS's code was not met, and at this point it is dangerous to proceed. Please report this error
to the BetterSMS developers.

userIdMatch is null.

Regards,
Laszlo

**Comment by markspolakovs** [comment]
That's generated on this line:

https://github.com/markspolakovs/BetterSMS/blob/master/src/util/libmsm/exercises.ts#L15

It means that we tried to get the user's ID from SMS but couldn't find it.

@lacicloud could you go to https://sms.eursc.eu/content/common/calendar_for_students.php, do a view source, put the HTML source in a pastebin/gist/whatever, and privately message it to me? Thank you!

**Comment by markspolakovs** [comment]
Per discussion by private message, apparently this appears when you use SMS from parential view. Unfortunately, BetterSMS does not support parental view and probably won't in the foreseeable future.
